name: plex_notifier
description: A sample command-line application.
version: 1.0.1
homepage: https://github.com/Arinono/plex-notifier

environment:
  sdk: '>=2.8.1 <3.0.0'

scripts:
  test: pub run test --reporter="expanded"
  test-full: pub run test --reporter="expanded" --coverage=coverage test/* && coverage:format_coverage -l -i coverage/test -o coverage/lcov.info --packages=.packages --report-on=lib && genhtml coverage/lcov.info -o coverage

dependencies:
  mime: ^0.9.6+3
  http: ^0.12.1
  args: ^1.5.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  mockito: ^4.1.1
  http_parser: ^3.1.4
  derry: ^0.1.1
  coverage: ^0.14.0

