name: plex_notifier
description: A sample command-line application.
version: 1.0.1
homepage: https://github.com/Arinono/plex-notifier

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  # path: ^1.7.0
  mime: ^0.9.6+3
  http: 0.12.1
  args: ^1.5.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
