FROM google/dart:2.8 as dart-runtime

WORKDIR /app

ARG DISCORD_CHANNEL_ID
ARG DISCORD_CLIENT_ID
ARG DISCORD_BOT_TOKEN

COPY pubspec.* /app/
RUN pub get
COPY . .
RUN pub get --offline
RUN pub global activate derry

CMD DISABLE_NOTIFIER=true DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID} DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN} DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID} derry run test-full

# bash <(curl -s https://codecov.io/bash -t $CODECOV_TOKEN)
