name: 'Build'

on: [push]

jobs:
  build:
    timeout-minutes: 5
    name: Build project
    runs-on: ubuntu-latest
    container:
      image:  google/dart:2.8
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Build
        run: dart2native -DDISCORD_CLIENT_ID="$DISCORD_CLIENT_ID" -DDISCORD_BOT_TOKEN="$DDISCORD_BOT_TOKEN" bin/main.dart
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
