name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  draft-release:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWD }}
          repository: arinono/plex-notifier
          tag_with_ref: true
          tags: latest
          build_args: DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }},DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
